"""update db

Revision ID: 6fa7efd8414c
Revises: 65cecbec5bed
Create Date: 2023-09-17 01:22:51.959192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa7efd8414c'
down_revision = '65cecbec5bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_hadir', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jumlah_hadir')

    # ### end Alembic commands ###
